### ISSUE TITLE
make data_files setup option work like cx freeze

### ISSUE THREAD

**Issue by timeyyy** [cloudmatrix/esky#108]
basically i think its cleaner to do
    `(folder, folder)`
    `(file, file)`

than
    `(folder, glob(r'.\folder\*.*')`
    `('', [file])`

it is also consistent with py2exe and cxfreeze and requires users to not have to modify there setup files.

are we cool this implement this?

**Comment by rfk** [comment]
`data_files` is a standard distutils option [1] so I think we should remain consistent with whatever its base semantics are; adding additional conveniences sounds fine though.  Do py2exe and cxfreeze use it in a non-distutils-standard way?

[1] https://docs.python.org/2/distutils/setupscript.html#installing-additional-files

**Comment by timeyyy** [comment]
actually it's only cx freeze that implements it the way i proposed.
its a bit different than standard distutils.
the concept of cxfreeze is a sequence of `(to, from)`

the concept of distutils is `(directory, [files]) `

cx freeze uses the option name `include_files`, 
mm i'm guessing passing the vales through like this
`options={"bdist_esky": {"freezer_options": { "include_files": INCLUDES}}}`
would work,

**Comment by rfk** [comment]
We could also support `include_files` in addition to `data_files`, changing the `get_data_files` method in esky/bdist_esky/__init__.py so that it looks for files in both places.

**Comment by timeyyy** [comment]
sounds good!

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
