### ISSUE TITLE
cxfreeze on windows - mscrvt

### ISSUE THREAD

**Issue by timeyyy** [cloudmatrix/esky#112]
**python3 test failing ( due to mscrvt bundling )**

this line is returning an empty list on Python3, when on py2 it doesn't
https://github.com/cloudmatrix/esky/blob/master/esky/bdist_esky/__init__.py#L604

ryan says:
`it's entirely possible that the manifest format has changed in newer releases. You could try just printing out the whole manifest_str and grepping for references to "CRT", might give some clues as to what's changed.`

**Comment by timeyyy** [comment]
the following is generated here https://github.com/cloudmatrix/esky/blob/master/esky/winres.py#l142

**so on python 2** 
```
<type 'str'>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.VC90.CRT" version="9.0.21022.8" processorArchitecture="x86" publicKeyToken="1fc8b3b9a1e18e3b"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```
**and on python3**
```
b'<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">\r\n  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">\r\n   
 <security>\r\n      
<requestedPrivileges>\r\n  
      <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>\r\n  
    </requestedPrivileges>\r\n  
  </security>\r\n
  </trustInfo>\r\n
</assembly>'
```
this fails also on master branch,
not really sure how to proceed.

**Comment by rfk** [comment]
Huh - maybe the MSCVRT stuff is no longer needed at all with python3?

**Comment by timeyyy** [comment]
when i install my app it doesn't work on windows without me install microsoft visual c++ 2010. I think this issue is solved if you include the mscvrt?

**Comment by timeyyy** [comment]
however i found this on the py2exe pypi page

The C-runtime library for Python 3 does NOT need a windows manifest any longer to load correctly (this is a feature of Python, not of py2exe)

**Comment by rfk** [comment]
Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
