### ISSUE TITLE
Unable to get admin rights

### ISSUE THREAD

**Issue by JPFrancoia** [cloudmatrix/esky#114]
Im trying to get admin rights through the function call `app.get_root()`. I need them because when my program is installed on the user's computer, the executable files are in the system files/directories. Ex: C:\Program Files.

But app.get_root() causes an exception on both Windows and Linux (I haven't tried yet on OSX).

On Linux:

```
Traceback (most recent call last):
  File "/home/djipey/informatique/python/ChemBrows/updater.py", line 59, in run
    self.app.get_root()
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 312, in get_root
    self.sudo_proxy.start()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 140, in start
    self.close()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 156, in close
    self.pipe.read()
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_base.py", line 123, in read
    raise EOFError
EOFError
```

So I modified sudo_base.py to get infos:

```
        self.check_connection()
        sz = self._read(4)
        print(len(sz))
        print(sz)
        if len(sz) < 4:
            raise EOFError
```

And when I run my program, I get:

```
0
b''
```

So I guess there is a problem with the object SecureStringPipe.

Also, I sometimes have another exception, still on Linux:

```
Traceback (most recent call last):
  File "/home/djipey/informatique/python/ChemBrows/updater.py", line 59, in run
    self.app.get_root()
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 312, in get_root
    self.sudo_proxy.start()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 136, in start
    msg = self.pipe.read()
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_base.py", line 121, in read
    sz = self._read(4)
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_unix.py", line 82, in _read
    return os.read(self.rfd,size)
OSError: [Errno 9] Mauvais descripteur de fichier
```

It randomly appears, but the first one is the main one.

On windows:

```
  File "C:\Users\djipey\Desktop\ChemBrows_freeze\updater.py", line 59, in run
    self.app.get_root()
  File "C:\Python34\lib\site-packages\esky\__init__.py", line 312, in get_root
    self.sudo_proxy.start()
  File "C:\Python34\lib\site-packages\esky\sudo\__init__.py", line 123, in start
    (self.proc,self.pipe) = spawn_sudo(self)
  File "C:\Python34\lib\site-packages\esky\sudo\__init__.py", line 83, in spawn_sudo
    return _impl.spawn_sudo(proxy)
  File "C:\Python34\lib\site-packages\esky\sudo\sudo_win32.py", line 313, in spawn_sudo
    execinfo.lpVerb = "runas"
TypeError: bytes or integer address expected instead of str instance
```

**Comment by timeyyy** [comment]
it's good we are giving the code base a work out haha. I believe i encountered similar errors when playing around with the function as well. How are you calling it? I haven't touched this code much, maybe ryan will have some pointers when he gets back from his travels at the end of the week.

**Comment by JPFrancoia** [comment]
I'm actually calling it from a PyQt GUI programm, but in a very simple way. It opens a window (gksudo, I guess) to ask for my password.

I realize this cannot work at all.

[Looking at the file](https://github.com/cloudmatrix/esky/blob/master/esky/sudo/sudo_base.py#L81), I can see the function _read is not implemented yet, and will return None.

So in the read fucntion:

```python
    def read(self):
        """Read the next string from the pipe.

        The expected data format is:  4-byte size, data, signature
        """
        self.check_connection()
        sz = self._read(4)
        if len(sz) < 4:
            raise EOFError
        sz = struct.unpack("I",sz)[0]
        data = self._read(sz)
        if len(data) < sz:
            raise EOFError
        sig = self._read(self._read_hmac.digest_size)
        self._read_hmac.update(data)
        if sig != self._read_hmac.digest():
            self.close()
            raise RuntimeError("mismatched hmac; terminating")
        return data
```

len(sz) will always be 0, and the function will fail with an EOFError exception.

**Comment by timeyyy** [comment]
when running the tests on Linux a window is thrown up asking for a password (this works successfully)

**Comment by JPFrancoia** [comment]
Yes, this part works successfully. But when I press enter in the window, I get the EOFError exception.

**Comment by timeyyy** [comment]
hitting enter runs fine for me when executing from test_esky.py , might be worth poking around and see what is happening differntly

**Comment by JPFrancoia** [comment]
How do you run the test ? I would like to try.

**Comment by timeyyy** [comment]
on master just do
`python2 -m pytest`
if esky is able to get root it will prompt you for your password
if u run the program with sudo it won't even need to ask you.

**Comment by JPFrancoia** [comment]
I tried, it runs, all the tests pass, but I'm not asked for a password:

```
 python2 -m pytest
==================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
rootdir: /home/djipey/informatique/python/esky, inifile: 
collected 38 items 

tests/test_esky.py ......................................

================================================================================= 38 passed in 12.02 seconds =================================================================================
```

**Comment by timeyyy** [comment]
im getting 40 tests on my system, run pytests with -v and see what is different

im guessing this is returning false for you...
https://github.com/cloudmatrix/esky/blob/master/esky/tests/test_esky.py#l202

platform linux2 -- Python 2.7.6 -- py-1.4.28 -- pytest-2.7.1 -- /usr/bin/python
rootdir: /home/alfa/Documents/git/esky, inifile:
collecting ... collected 40 items

test_esky.py::TestEsky::test_esky_cxfreeze PASSED
test_esky.py::TestEsky::test_esky_cxfreeze_needsroot PASSED
test_esky.py::TestEsky::test_esky_lock_breaking PASSED
test_esky.py::TestEsky::test_esky_locking PASSED
test_esky.py::TestFSTransact::test_copy_dir PASSED
test_esky.py::TestFSTransact::test_copy_dir_exists PASSED
test_esky.py::TestFSTransact::test_copy_dir_over_file PASSED
test_esky.py::TestFSTransact::test_copy_file PASSED
test_esky.py::TestFSTransact::test_copy_file_over_dir PASSED
test_esky.py::TestFSTransact::test_move_dir PASSED
test_esky.py::TestFSTransact::test_move_dir_exists PASSED
test_esky.py::TestFSTransact::test_move_dir_over_file PASSED
test_esky.py::TestFSTransact::test_move_file PASSED
test_esky.py::TestFSTransact::test_move_file_over_dir PASSED
test_esky.py::TestFSTransact::test_move_file_with_unicode_name PASSED
test_esky.py::TestFSTransact::test_no_move_outside_root PASSED
test_esky.py::TestFSTransact::test_remove PASSED
test_esky.py::TestFSTransact::test_remove_abort PASSED
test_esky.py::TestPatch::test_apply_patch_fail_when_sourcefile_has_been_deleted PASSED
test_esky.py::TestPatch::test_apply_patch_old PASSED
test_esky.py::TestPatch::test_apply_patch_with_filelist PASSED
test_esky.py::TestPatch::test_apply_patch_with_filelist_removal_of_files_not_in_filelist PASSED
test_esky.py::TestPatch::test_copying_multiple_targets_from_a_single_sibling PASSED
test_esky.py::TestPatch::test_diffing_back_and_forth PASSED
test_esky.py::TestPatch::test_patch_bigfile PASSED
test_esky.py::TestPatch_cxbsdiff::test_apply_patch_fail_when_sourcefile_has_been_deleted PASSED
test_esky.py::TestPatch_cxbsdiff::test_apply_patch_old PASSED
test_esky.py::TestPatch_cxbsdiff::test_apply_patch_with_filelist PASSED
test_esky.py::TestPatch_cxbsdiff::test_apply_patch_with_filelist_removal_of_files_not_in_filelist PASSED
test_esky.py::TestPatch_cxbsdiff::test_copying_multiple_targets_from_a_single_sibling PASSED
test_esky.py::TestPatch_cxbsdiff::test_diffing_back_and_forth PASSED
test_esky.py::TestPatch_cxbsdiff::test_patch_bigfile PASSED
test_esky.py::TestPatch_pybsdiff::test_apply_patch_fail_when_sourcefile_has_been_deleted PASSED
test_esky.py::TestPatch_pybsdiff::test_apply_patch_old PASSED
test_esky.py::TestPatch_pybsdiff::test_apply_patch_with_filelist PASSED
test_esky.py::TestPatch_pybsdiff::test_apply_patch_with_filelist_removal_of_files_not_in_filelist PASSED
test_esky.py::TestPatch_pybsdiff::test_copying_multiple_targets_from_a_single_sibling PASSED
test_esky.py::TestPatch_pybsdiff::test_diffing_back_and_forth PASSED
test_esky.py::TestPatch_pybsdiff::test_patch_bigfile PASSED
test_esky.py::TestFilesDiffer::test_files_differ PASSED

========================== 40 passed in 94.47 seconds

**Comment by JPFrancoia** [comment]
Of course, I only have 38 items, and not the ones I want:

```
 python2 -m pytest -v       
==================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python2
cachedir: .cache
rootdir: /home/djipey/informatique/python/esky, inifile: 
collected 38 items 

esky/tests/test_esky.py::TestEsky::test_esky_lock_breaking PASSED
esky/tests/test_esky.py::TestEsky::test_esky_locking PASSED
esky/tests/test_esky.py::TestFSTransact::test_copy_dir PASSED
esky/tests/test_esky.py::TestFSTransact::test_copy_dir_exists PASSED
esky/tests/test_esky.py::TestFSTransact::test_copy_dir_over_file PASSED
esky/tests/test_esky.py::TestFSTransact::test_copy_file PASSED
esky/tests/test_esky.py::TestFSTransact::test_copy_file_over_dir PASSED
esky/tests/test_esky.py::TestFSTransact::test_move_dir PASSED
esky/tests/test_esky.py::TestFSTransact::test_move_dir_exists PASSED
esky/tests/test_esky.py::TestFSTransact::test_move_dir_over_file PASSED
esky/tests/test_esky.py::TestFSTransact::test_move_file PASSED
esky/tests/test_esky.py::TestFSTransact::test_move_file_over_dir PASSED
esky/tests/test_esky.py::TestFSTransact::test_move_file_with_unicode_name PASSED
esky/tests/test_esky.py::TestFSTransact::test_no_move_outside_root PASSED
esky/tests/test_esky.py::TestFSTransact::test_remove PASSED
esky/tests/test_esky.py::TestFSTransact::test_remove_abort PASSED
esky/tests/test_esky.py::TestPatch::test_apply_patch_fail_when_sourcefile_has_been_deleted PASSED
esky/tests/test_esky.py::TestPatch::test_apply_patch_old PASSED
esky/tests/test_esky.py::TestPatch::test_apply_patch_with_filelist PASSED
esky/tests/test_esky.py::TestPatch::test_apply_patch_with_filelist_removal_of_files_not_in_filelist PASSED
esky/tests/test_esky.py::TestPatch::test_copying_multiple_targets_from_a_single_sibling PASSED
esky/tests/test_esky.py::TestPatch::test_diffing_back_and_forth PASSED
esky/tests/test_esky.py::TestPatch::test_patch_bigfile PASSED
esky/tests/test_esky.py::TestPatch_cxbsdiff::test_apply_patch_fail_when_sourcefile_has_been_deleted PASSED
esky/tests/test_esky.py::TestPatch_cxbsdiff::test_apply_patch_old PASSED
esky/tests/test_esky.py::TestPatch_cxbsdiff::test_apply_patch_with_filelist PASSED
esky/tests/test_esky.py::TestPatch_cxbsdiff::test_apply_patch_with_filelist_removal_of_files_not_in_filelist PASSED
esky/tests/test_esky.py::TestPatch_cxbsdiff::test_copying_multiple_targets_from_a_single_sibling PASSED
esky/tests/test_esky.py::TestPatch_cxbsdiff::test_diffing_back_and_forth PASSED
esky/tests/test_esky.py::TestPatch_cxbsdiff::test_patch_bigfile PASSED
esky/tests/test_esky.py::TestPatch_pybsdiff::test_apply_patch_fail_when_sourcefile_has_been_deleted PASSED
esky/tests/test_esky.py::TestPatch_pybsdiff::test_apply_patch_old PASSED
esky/tests/test_esky.py::TestPatch_pybsdiff::test_apply_patch_with_filelist PASSED
esky/tests/test_esky.py::TestPatch_pybsdiff::test_apply_patch_with_filelist_removal_of_files_not_in_filelist PASSED
esky/tests/test_esky.py::TestPatch_pybsdiff::test_copying_multiple_targets_from_a_single_sibling PASSED
esky/tests/test_esky.py::TestPatch_pybsdiff::test_diffing_back_and_forth PASSED
esky/tests/test_esky.py::TestPatch_pybsdiff::test_patch_bigfile PASSED
esky/tests/test_esky.py::TestFilesDiffer::test_files_differ PASSED

================================================================================= 38 passed in 12.73 seconds =================================================================================
```

**Comment by timeyyy** [comment]
aha... so you are also missing
test_esky_cxfreeze
have you got cxfreeze installed on python2?

**Comment by JPFrancoia** [comment]
I hadn't, thanks. Now I have 40 items too.

test_esky_cxfreeze_needsroot fails, as expected:

```
python2 -m pytest -v
==================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python2
cachedir: .cache
rootdir: /home/djipey/informatique/python/esky, inifile: 
collected 40 items 

esky/tests/test_esky.py::TestEsky::test_esky_cxfreeze_needsroot FAILED
```

I was asked my password this time. Here is the log for the test:

[out.txt](https://github.com/cloudmatrix/esky/files/53250/out.txt)

**Comment by timeyyy** [comment]
interesting... and if you run it with sudo?

**Comment by JPFrancoia** [comment]
It PASSED

**Comment by timeyyy** [comment]
:+1: do you have any idea why it would work on my system and not yours?

**Comment by JPFrancoia** [comment]
Because I'm very lucky ?

Nope, right now I don't have a clue. I'm running Manjaro Linux. And you ? Coud it be possible that my program can still manage the update process on another distribution ?

**Comment by timeyyy** [comment]
I'm on Ubuntu 14.10 x86.
Actually i think cxfreeze doesn't bundle any of the c libraries that it used when it compiles, so you will only be able to install and run your app on a computer that has the dlls of the same version as most of the time there are backwards incompatible changes. 

https://en.wikipedia.org/wiki/Dependency_hell

it's a big issue on linux, there are no guarantees your app will even work on the next or previous release of the same os you built it on. Might be better to go with source distribution on linux...

**Comment by JPFrancoia** [comment]
Hum I don't know, I applied a fix on sudo_win32 to fix the issue I mentionned at first. Still a bytes thing.

After that, I get the same error on Windows AND on Linux. So the issue is not platform specific.

**Comment by JPFrancoia** [comment]
I actually get (randomly) one of the following exception when I try to use ```app.get_root()```

```
Traceback (most recent call last):
  File "/home/djipey/informatique/python/ChemBrows/updater.py", line 60, in run
    self.app.get_root()
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 312, in get_root
    self.sudo_proxy.start()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 136, in start
    msg = self.pipe.read()
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_base.py", line 121, in read
    sz = self._read(4)
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_unix.py", line 83, in _read
    return os.read(self.rfd,size)
TypeError: an integer is required (got type NoneType)
```

OR

```
Traceback (most recent call last):
  File "/home/djipey/informatique/python/ChemBrows/updater.py", line 59, in run
    self.app.get_root()
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 312, in get_root
    self.sudo_proxy.start()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 140, in start
    self.close()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 156, in close
    self.pipe.read()
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_base.py", line 123, in read
    raise EOFError
EOFError
```
OR

```
Traceback (most recent call last):
  File "/home/djipey/informatique/python/ChemBrows/updater.py", line 60, in run
    self.app.get_root()
  File "/usr/lib/python3.5/site-packages/esky/__init__.py", line 312, in get_root
    self.sudo_proxy.start()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 140, in start
    self.close()
  File "/usr/lib/python3.5/site-packages/esky/sudo/__init__.py", line 157, in close
    self.pipe.write(b("CLOSE"))
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_base.py", line 141, in write
    self._write(struct.pack("I",len(data)))
  File "/usr/lib/python3.5/site-packages/esky/sudo/sudo_unix.py", line 86, in _write
    return os.write(self.wfd,data)
BrokenPipeError: [Errno 32] Relais brisé (pipe)
```

**Comment by JPFrancoia** [comment]
super @rfk , any idea ?

**Comment by timeyyy** [comment]
intersting... i also recieved broken pipe errors when using travis ci which i was unable to fix, i just disabled the tests.. rfk will be busy until the end of the week but nice work!

**Comment by JPFrancoia** [comment]
Ok, I'll try to figure something out by myself until then.

I would say something in SecureStringPipe is closed before ```self.pipe.read()```

But there might are several issues here.

**Comment by timeyyy** [comment]
i have never had the issue on my system, on travis server however we receive
```
  File "/tmp/tmpkF5fDk/scripts/script1.py", line 83, in <module>
  File "/home/travis/build/timeyyy/esky/esky/__init__.py", line 311, in get_root
    self.sudo_proxy.start()
  File "/home/travis/build/timeyyy/esky/esky/sudo/__init__.py", line 140, in start
    self.close()
  File "/home/travis/build/timeyyy/esky/esky/sudo/__init__.py", line 156, in close
    self.pipe.read()
  File "/home/travis/build/timeyyy/esky/esky/sudo/sudo_base.py", line 123, in read
    raise EOFError
EOFError
```

this is also the same error but we get this error message if we remove print statements from script1.py
```
  File "/home/travis/build/timeyyy/esky/esky/__init__.py", line 311, in get_root
    self.sudo_proxy.start()
  File "/home/travis/build/timeyyy/esky/esky/sudo/__init__.py", line 125, in start
    raise RuntimeError("sudo helper process terminated unexpectedly")
RuntimeError: sudo helper process terminated unexpectedly
```

**Comment by JPFrancoia** [comment]
Where does script1.py comes from (can I see it ?) ? And how can a print statement in script1.py change the final exception we get ?

**Comment by timeyyy** [comment]
esky/tests/eskytester/script1.py ( this is built into an esky run using subprocess.Popen)
I think the traceback is captured differntly by subprocess.Popen if we print to stdout during execution of the process (i'm not sure though)

**Comment by timeyyy** [comment]
ok so the first thing i'm noticing on travis ci is that if i turn the sudo option off for travis ci,
`esky.sudo.can_get_root()` still returns true even thought we cannot get root.

This gives the eoferror, i also receive the eoferror when sudo is enabled though.

How do i go about starting python with different permissions on my local machine?

**Comment by JPFrancoia** [comment]
Hum I'm not sure I really understand the whole process of Esky getting the sudo rights. But the fact that can_get_root() will always return True is not a problem, is it ? The question is indeed why you don't observe this behaviour on your machine.

**Comment by timeyyy** [comment]
i'm not an expert unfortunately. If we can find out how to reproduce the problem on my system i think it will take us a step in the right direction.

**Comment by JPFrancoia** [comment]
32 bit python ? Why ? So you have Ubuntu x86 and windows 7.

You don't have any problem getting root with ubuntu, right ?
What about windows ? What architecture do you run, and do you encounter the problem ?

**Comment by timeyyy** [comment]
i was having a hard time installing some libraries in the 64bit :), all my python versions are 32bit,

**Comment by timeyyy** [comment]
ok we could be on the right path, i just tested on appveyor and the x64 fails while the x86 works, https://ci.appveyor.com/project/tim83455/esky-vaa8s/build/1.0.88.

**Comment by JPFrancoia** [comment]
Ok, so from what you said:

>this is also the same error but we get this error message if we ADD print statements from script1.py

```
  File "/home/travis/build/timeyyy/esky/esky/__init__.py", line 311, in get_root
    self.sudo_proxy.start()
  File "/home/travis/build/timeyyy/esky/esky/sudo/__init__.py", line 125, in start
    raise RuntimeError("sudo helper process terminated unexpectedly")
RuntimeError: sudo helper process terminated unexpectedly
```

I looked at l125 of __init__.py:

```python
    def start(self):
        (self.proc,self.pipe) = spawn_sudo(self)
        if self.proc.poll() is not None:
            raise RuntimeError("sudo helper process terminated unexpectedly")
```

so left.proc is not operational. proc is returned by the spawn_sudo function of the sudo_* files.

Here is the one of sudo_unix.py:

```python
def spawn_sudo(proxy):
    """Spawn the sudo slave process, returning proc and a pipe to message it."""
    rnul = open(os.devnull,"r")
    wnul = open(os.devnull,"w")
    pipe = SecureStringPipe()
    c_pipe = pipe.connect()
    if not getattr(sys,"frozen",False):
        exe = [sys.executable,"-c","import esky; esky.run_startup_hooks()"]
    elif os.path.basename(sys.executable).lower() in ("python","pythonw"):
        exe = [sys.executable,"-c","import esky; esky.run_startup_hooks()"]
    else:
        if not esky._startup_hooks_were_run:
            raise OSError(None,"unable to sudo: startup hooks not run")
        exe = [sys.executable]
    args = ["--esky-spawn-sudo"]
    args.append(base.b64pickle(proxy))
    # Look for a variety of sudo-like programs
    sudo = None
    display_name = "%s update" % (proxy.name,)
    if "DISPLAY" in os.environ:
        sudo = find_exe("gksudo","-k","-D",display_name,"--")
        if sudo is None:
            sudo = find_exe("kdesudo")
        if sudo is None:
            sudo = find_exe("cocoasudo","--prompt='%s'" % (display_name,))
    if sudo is None:
        sudo = find_exe("sudo")
    if sudo is None:
        sudo = []
    # Make it a slave process so it dies if we die
    exe = sudo + exe + esky.slaveproc.get_slave_process_args() + args
    # Pass the pipe in environment vars, they seem to be harder to snoop.
    env = os.environ.copy()
    env["ESKY_SUDO_PIPE"] = base.b64pickle(c_pipe)
    # Spawn the subprocess
    kwds = dict(stdin=rnul,stdout=wnul,stderr=wnul,close_fds=True,env=env)
    proc = KillablePopen(exe,**kwds)
    return (proc,pipe)
```

The bug is somewhere in this function (I think).

**Comment by JPFrancoia** [comment]
I'm investigating as hell:

I commented 2 lines in sudo_base.py:

```python
    def read(self):
        """Read the next string from the pipe.

        The expected data format is:  4-byte size, data, signature
        """
        self.check_connection()
        sz = self._read(4)
        # if len(sz) < 4:
            # raise EOFError
```

To get rid of the EOFError and get more info:

```
File "/home/djipey/informatique/python/esky/esky/sudo/sudo_base.py", line 125, in read
    sz = struct.unpack("I",sz)[0]
struct.error: unpack requires a string argument of length 4
```
But be careful, the error doesn't actually come from sudo_base.py (the file containing the parent class), but from sudo_unix.py.

Looking at sudo_unix.py:

```python
    def _read(self,size):
        print(self.rfd)
        print(size)
        print(os.read(self.rfd, size))
        return os.read(self.rfd,size)
```
And I get:
14
4
and an empty string !

Shouldn't os.read return something ?

**Comment by timeyyy** [comment]
on my working system i get
13
4
and and empty string

**Comment by JPFrancoia** [comment]
On the system that gives the EOFError ? (I mean, the one with 32bit libs ?)

**Comment by JPFrancoia** [comment]
How is it possible ?? It should crash with:

```python
        sz = self._read(4)
        # if len(sz) < 4:
            # raise EOFError
        sz = struct.unpack("I",sz)[0]
        data = self._read(sz)
```
in sudo_linux.py. Your variable sz is empty if _read returns an empty string.

**Comment by timeyyy** [comment]
All tests run fun on my 32bit system, this is the system im talking about

**Comment by JPFrancoia** [comment]
That's very strange. Could you check the value of ```sz``` after ```sz = self._read(4)``` in sudo_linux.py please ?

**Comment by JPFrancoia** [comment]
For future us and whoever will read this:

The problem (for now) seems to come from from the file descriptor. It seems I can not get the right value.

While (most of the time) I get ```self.rfd``` = 14, tim gets 13.

**Comment by JPFrancoia** [comment]
I think we really need @rfk , we didn't move much for a while.

**Comment by timeyyy** [comment]
### Digging through old commits..

i found testing older commits than this kept locking up ( something this commit fixes),

```
commit 3bd459b909a8a5007d069c5f4a59d00c91120e48
Author: Ryan Kelly <ryan@rfk.id.au>
Date:   Mon Sep 5 10:47:03 2011 +1000

    esky.sudo: monitor helper process to avoid deadlock if it dies
```

we are still seeings the same behavior
 - random error messages
 - works on x86 python2
 - fails on x64 python2

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
