### ISSUE TITLE
Dealing with connection dropped errors

### ISSUE THREAD

**Issue by kollivier** [cloudmatrix/esky#12]
Since urllib.urlopen uses a blocking socket, if the internet connection drops mid-download, it will hang forever, and you have to force quit the application to retry the download. This also means you cannot cancel the download midway through if, say, you suddenly need to reboot or something. I could not find a way to get the sockets used by urllib.urlopen to be non-blocking or timeout properly, and it looked like this was just part of how it was designed. After some hacking, I found that using urllib.urlretrieve avoided this problem, but the reporthook callback approach doesn't work well with the generator approach fetch_file_iter uses. 

What would be the best way to approach this?

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
