### ISSUE TITLE
continous integration appveyor

### ISSUE THREAD

**Issue by timeyyy** [cloudmatrix/esky#120]
Waiting on py2exe to release some wheels, pypi only has py2 x86

Could try unofficial rrepos or compiling from source if they do not do it...

**Comment by topic2k** [comment]
https://pypi.python.org/pypi/py2exe/0.9.2.2    (python 3 version)

**Comment by timeyyy** [comment]
those will definitletly come in handy when we get the tests on py3, main problem atm is no py2exe wheels for py27 on x64 architecture

**Comment by timeyyy** [comment]
@rfk can you link your account with appveyor and make a project with esky, and also edit the relevant parts of the status link in the readme so it points to the right place ( i added some custom text so we know which build it is). You can find the link information in settings-> badge status. Also on the general tab please enable rolling builds ( this will cancel any current tests if we do a new push) (tests are quite slow so)

**Comment by timeyyy** [comment]
Due to the slow nature of wheels from py2exe and cxfreeze, need to compile from source, 
Some issues
- How to extract tar.gz on windows.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
