### ISSUE TITLE
Error while finding dll

### ISSUE THREAD

**Issue by RussTheAerialist** [cloudmatrix/esky#13]
When trying to use bdist_esky on windows, it seems to fail to find libzmq.dll (when using the pyzmq library).  I get the following error:

> *** finding dlls needed ***
> error: libzmq.dll: No such file or directory

I was also have this problem with py2exe (so it appears that the problem might actually be related to py2exe), so I had to add the "dll_excludes" in the options['py2exe'] dict, which, seemingly, should have caused it to work in esky also (given the examples provided in github).  I then include that dll in the data_files argument.  Something like the following is what my call to setup looks like:

```python
setup(name="tigger",
      version="0.1.1",
      packages = find_packages(),
      scripts=['tigger.py', 'tigger_service.py', 'tigger_master.py'], #for esky
      # console=['tigger.py', 'tigger_service.py', 'tigger_master.py'], #for py2exe
      options={"bdist_esky":{
      }, "py2exe": {
        "dll_excludes": ['libzmq.dll'],
        "includes": ['zmq.utils.strtypes',
                     'zmq.utils.jsonapi']
        }
      },
      install_requires = [
        'wmi>=1.4.9',
        'pyzmq>=2.1.11',
        'pyyaml>=3.09',
      ],
      data_files = [
        ('', ('C:\\Python27\\Lib\\site-packages\\zmq\\libzmq.dll', ))
      ],
)
```

If I have the console line above, and use py2exe, everything works fine.  But as configured above, and with bdist_esky, I'm still getting the error about not being able to find libzmq.dll.

REPRO STEPS:

* Install pyzmq using the an installer from here: https://github.com/zeromq/pyzmq/downloads (I'm using 32bit, Python 2.7)
* Use a simple python script that just imports zmq (doesn't have to do anything else really)
* Create a setup.py as above
* run python setup.py bdest_esky

RESULTS:

> *** finding dlls needed ***
> error: libzmq.dll: No such file or directory

EXPECTED RESULTS:

Fully built esky bdist package.

**Comment by timeyyy** [comment]
seems like this is py2exe's issues, closed due to inactivity
