### ISSUE TITLE
unable to run bootrap file using py2exe and python3.4 

### ISSUE THREAD

**Issue by timeyyy** [cloudmatrix/esky#131]
#### original issue posted from @topic2k

On python3 the script is freezed/zipped, but when i run it, it chrashes and gives me this error

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
```

This error is with the bootstrap exe. The exe in the subfolder runs fine.

related to #104 but for windows

**Comment by timeyyy** [comment]
Originally posted by @rfk 
Over in #104, we figured out a minimal set of modules that must be available to python during its startup sequence.  I think this is a new requirement for python3, related to bootstrapping the `io` module and `sys.stdin` and similar.  The list is:

```
_weakrefset.pyc abc.pyc     codecs.pyc  encodings   io.pyc
```

So, we need to find a way to make these available to the py2exe bootstrap exe.  This probably means creating a `library.zip` or similar in the top-level bootstrap env, or perhaps appending them to the bootstrap executable itself.  Unfortunately I don't have access to a windows box at the moment, but if anyone's feeling adventurous, I can give you some pointers on how move ahead with this. 

In fact, there's a comment in f_py2exe that says "There's no need to copy library.zip into the bootstrap env...". One way to see if this will help fix the problem, would be to copy the library.zip from the version subfolder into the bootstrap env, and see if that lets things run.

**Comment by timeyyy** [comment]
@rfk 
how did you skip the encoding error and get to the subsequent error in issue #104 ?

No combination of unzipping the encoding files or sitting the library.zip next to the bootrap exe managed to work.

I will confirm, but if i make the app update itself (by bypassing the bootsrap and selecting the version manually), it creates some folders and does its magic, after that the bootstrap works...

**Comment by timeyyy** [comment]
#116 is also to do with the bootstrap not working when a particular module is present

**Comment by rfk** [comment]
Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
