### ISSUE TITLE
Error for running the tutorial esky-master\tutorial\stage0\ on my Windows10

### ISSUE THREAD

**Issue by xavierzhao** [cloudmatrix/esky#138]
Does it support Python 3.4? How can I do? 

Thanks & Best Regards

C:\Users\Administrator\Desktop\esky-master\tutorial\stage0>python setup.py build
running build
running build_exe
copying D:\Python\lib\site-packages\cx_Freeze\bases\Console.exe -> build\exe.win-amd64-3.4\example.exe
copying C:\WINDOWS\SYSTEM32\python34.dll -> build\exe.win-amd64-3.4\python34.dll
Stamped: build\exe.win-amd64-3.4\example.exe
writing zip file build\exe.win-amd64-3.4\library.zip

  Name                      File
  ----                      ----
m BUILD_CONSTANTS
m __future__                D:\Python\lib\__future__.py
m _bootlocale
m _bz2                      D:\Python\DLLs\_bz2.pyd
m _codecs
m _codecs_cn
m _codecs_hk
m _codecs_iso2022
m _codecs_jp
m _codecs_kr
m _codecs_tw
m _collections
m _collections_abc
m _datetime
m _dummy_thread
m _functools
m _heapq
m _imp
m _io
m _locale
m _multibytecodec
m _operator
m _sre
m _stat
m _string
m _strptime
m _struct
m _thread
m _threading_local
m _warnings
m _weakref
m _weakrefset
m abc
m argparse
m atexit
m base64
m binascii
m builtins
m bz2
m calendar
m codecs
P collections
m collections.abc
m contextlib
m copy
m copyreg
m cx_Freeze__init__         D:\Python\lib\site-packages\cx_Freeze\initscripts\Console.py
m datetime
m dummy_threading
P encodings
m encodings.aliases
m encodings.ascii
m encodings.base64_codec
m encodings.big5
m encodings.big5hkscs
m encodings.bz2_codec
m encodings.charmap
m encodings.cp037
m encodings.cp1006
m encodings.cp1026
m encodings.cp1125
m encodings.cp1140
m encodings.cp1250
m encodings.cp1251
m encodings.cp1252
m encodings.cp1253
m encodings.cp1254
m encodings.cp1255
m encodings.cp1256
m encodings.cp1257
m encodings.cp1258
m encodings.cp273
m encodings.cp424
m encodings.cp437
m encodings.cp500
m encodings.cp65001
m encodings.cp720
m encodings.cp737
m encodings.cp775
m encodings.cp850
m encodings.cp852
m encodings.cp855
m encodings.cp856
m encodings.cp857
m encodings.cp858
m encodings.cp860
m encodings.cp861
m encodings.cp862
m encodings.cp863
m encodings.cp864
m encodings.cp865
m encodings.cp866
m encodings.cp869
m encodings.cp874
m encodings.cp875
m encodings.cp932
m encodings.cp949
m encodings.cp950
m encodings.euc_jis_2004
m encodings.euc_jisx0213
m encodings.euc_jp
m encodings.euc_kr
m encodings.gb18030
m encodings.gb2312
m encodings.gbk
m encodings.hex_codec
m encodings.hp_roman8
m encodings.hz
m encodings.idna
m encodings.iso2022_jp
m encodings.iso2022_jp_1
m encodings.iso2022_jp_2
m encodings.iso2022_jp_2004
m encodings.iso2022_jp_3
m encodings.iso2022_jp_ext
m encodings.iso2022_kr
m encodings.iso8859_1
m encodings.iso8859_10
m encodings.iso8859_11
m encodings.iso8859_13
m encodings.iso8859_14
m encodings.iso8859_15
m encodings.iso8859_16
m encodings.iso8859_2
m encodings.iso8859_3
m encodings.iso8859_4
m encodings.iso8859_5
m encodings.iso8859_6
m encodings.iso8859_7
m encodings.iso8859_8
m encodings.iso8859_9
m encodings.johab
m encodings.koi8_r
m encodings.koi8_u
m encodings.latin_1
m encodings.mac_arabic
m encodings.mac_centeuro
m encodings.mac_croatian
m encodings.mac_cyrillic
m encodings.mac_farsi
m encodings.mac_greek
m encodings.mac_iceland
m encodings.mac_latin2
m encodings.mac_roman
m encodings.mac_romanian
m encodings.mac_turkish
m encodings.mbcs
m encodings.palmos
m encodings.ptcp154
m encodings.punycode
m encodings.quopri_codec
m encodings.raw_unicode_escape
m encodings.rot_13
m encodings.shift_jis
m encodings.shift_jis_2004
m encodings.shift_jisx0213
m encodings.tis_620
m encodings.undefined
m encodings.unicode_escape
m encodings.unicode_internal
m encodings.utf_16
m encodings.utf_16_be
m encodings.utf_16_le
m encodings.utf_32
m encodings.utf_32_be
m encodings.utf_32_le
m encodings.utf_7
m encodings.utf_8
m encodings.utf_8_sig
m encodings.uu_codec
m encodings.zlib_codec
m errno
m example__main__           example.py
m functools
m gc
m genericpath
m gettext
m heapq
P importlib                 D:\Python\lib\importlib\__init__.py
m importlib._bootstrap
m io
m itertools
m keyword
m linecache
m locale
m math
m nt
m ntpath
m operator
m optparse
m os
m posixpath
m quopri
m re
m reprlib
m sre_compile
m sre_constants
m sre_parse
m stat
m string
m stringprep
m struct
m sys
m textwrap
m threading
m time
m token
m tokenize
m traceback
m types
m unicodedata               D:\Python\DLLs\unicodedata.pyd
m warnings
m weakref
m zipimport
m zlib

Missing modules:
? _dummy_threading imported from dummy_threading
? ce imported from os
? doctest imported from heapq
? getopt imported from base64, quopri
? org.python.core imported from copy
? os.path imported from os
? posix imported from os
? pwd imported from posixpath
? subprocess imported from os
This is not necessarily a problem - the modules may not be needed on this platform.

copying D:\Python\DLLs\_bz2.pyd -> build\exe.win-amd64-3.4\_bz2.pyd
copying D:\Python\DLLs\unicodedata.pyd -> build\exe.win-amd64-3.4\unicodedata.pyd

**Comment by timeyyy** [comment]
This part of the tutorial is just to make sure the underlying freezer is setup correctly. If.you cannot find a fix for cxfreeze(what the tutorial uses) you could try py2exe

**Comment by xavierzhao** [comment]
@timeyyy thanks, This is not necessarily a problem - the modules may not be needed on this platform.
