### ISSUE TITLE
Error for running python setup.py bdist_esky

### ISSUE THREAD

**Issue by xavierzhao** [cloudmatrix/esky#139]
D:\sources\python\gc>python setup.py bdist_esky
running bdist_esky
error: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp_urqt8tf\scripts\main.py'

Here is my setup.py:

from esky import bdist_esky
from esky.bdist_esky import Executable  
from distutils.core import setup

executables = [Executable('main.py', icon='gc.ico', gui_only=True)]

setup(  
    name='somename',
    version='0.1',  
    scripts=executables, 
    options = {"bdist_esky": {
                "freezer_module":"cxfreeze"}
                }
)

Thanks for your help

**Comment by timeyyy** [comment]
i am guessing the Chinese characters say missing file or directory?

The Executable class is looking relative to your current working directory instead of the more intuitive relative directory to the file, if you want to make a pull request for this i would accept it.

The work around is to make an absolute path to your file.
```python
here = os.path.basename(__file__)
os.path.abspath(os.path.join(here, 'main.py'))
```

**Comment by xavierzhao** [comment]
@timeyyy not missing file or directory, it says `[WinError 32] The process cannot access the file because it is being used by another process`

**Comment by timeyyy** [comment]
Did you get through the tutorial ok? Did you install esky from pypi or from github?

**Comment by kinnarr** [comment]
It looks like the same error as in issue #57

**Comment by timeyyy** [comment]
Are you able to freeze your app with cxfreeze?

**Comment by xavierzhao** [comment]
@timeyyy I am install esky from pypip and I can run my app with cxfreeze.

**Comment by xavierzhao** [comment]
tutorial is ok.

**Comment by timeyyy** [comment]
@xavierzhao is it possible for you to zip the files so i can test them?

**Comment by rfk** [comment]
Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
