### ISSUE TITLE
esky in windows enviornment

### ISSUE THREAD

**Issue by uttam028** [cloudmatrix/esky#145]
I have included esky in one of my python project, it works fine in mac version (Thanks for this cool stuff).  But it is not working in windows environment, I am getting  "No frozen version found" error. I followed Ryan's talk in the Pycon where he was showing esky in windows environment. Does it work in windows 10 platform?

**Comment by timeyyy** [comment]
Hi, there are a few bugs floating around with esky, i need to update the readme. My main problem at the moment is that cxfreeze is really hard to get working on linux. Some small fixed could be made to make it work correctly on python3.

I am in the process of switching over to pyinstaller and trying pyupdater.

**Comment by JMSwag** [comment]
[PyInstaller](https://github.com/pyinstaller/pyinstaller) - [PyUpdater](https://github.com/JMSwag/PyUpdater)

**Comment by nstanoszek** [comment]
I prefer PyInstaller as well, but with PyInstaller---are you able to successfully compile Celery to execute a celery application??  When I run celery after, it says that the App isn't found.  Thoughts?

**Comment by timeyyy** [comment]
Try asking over on the pyinstaller github page, there is also slot of existing info for making certain libraries package correctly

**Comment by nstanoszek** [comment]
Cool will do. I know when I do pyinstaller it compiles but does work...but esky has this stupid "in use" error with celery. Ugh!

Thanks!

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
