### ISSUE TITLE
tutorials fail 

### ISSUE THREAD

**Issue by acbeers** [cloudmatrix/esky#149]
On tutorial stage 1, using py2app as a freezer, the built app will fail to launch because fcntl isn't found.  I have this failure both on OSX 10.10.5 and OSX 10.11.6.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
