### ISSUE TITLE
locale.getdefaultlocale() returns None

### ISSUE THREAD

**Issue by BoboTiG** [cloudmatrix/esky#151]
Hello,

Does Esky change something with the `locale.getdefaultlocale()` behavior?
I tried on several different OS and I got good results. But from within an Esky built on macOS, I get `(None, None)`. The same script outside Esky gives me `('fr_FR', 'UTF-8')`.

Do you have an idea what is going on here?

Thank you.

PS: setting the system locale does not change anything:

    locale.setlocale(locale.LC_ALL, '')

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
