### ISSUE TITLE
Startup error under Windows XP

### ISSUE THREAD

**Issue by david-hughes** [cloudmatrix/esky#19]
An application I built using Esky under 64 bit Windows 7 raises the error " Unable to Locate Component - This application has failed to start because MSVCR90.dll was not found" when I run it using Windows XP. The VC90 files are there in  Microsoft.VC90.CRT folders both at the upper application level and within appdata. They are dated 31 Dec 2011. Rebuilding the application in XP itself produces the same error, although now the dlls are dated 7 November 2007. 

If I start the application using appdata\appname-version.win32\app.exe it runs OK. This is fine as a temporary work around but the path to it is version dependent. I am probably doing something wrong in the setup.py that builds it - any pointers as to what that might be?

Regards, David

**Comment by timeyyy** [comment]
@david-hughes is there actually anything we can do/ that you would suggest to improve the situation here or should i close this?

**Comment by david-hughes** [comment]
@timeyyy I have had several hundred users of this app since 2012 with no reports of any problems - well, not this one anyway! So I think it can be quietly closed and forgotten.
