### ISSUE TITLE
Unittests fail when running from the command line

### ISSUE THREAD

**Issue by aodj** [cloudmatrix/esky#26]
There's no explanation on exactly how to run the unittests, so after installing esky as an egg (using easy_install), attempting to run the unittests from the command line will error on several tests due to an inability to resolve the directory name of __file__.

I'm running them on the Windows command line using `python -m unittest esky.tests.test_esky` and get this as output (for 8 tests)

    ======================================================================
    ERROR: test_esky_py2exe (esky.tests.test_esky.TestEsky)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "esky\tests\test_esky.py", line 90, in test_esky_py2exe
        self._run_eskytester({"bdist_esky":{"freezer_module":"py2exe"}})
      File "esky\tests\test_esky.py", line 223, in _run_eskytester
        shutil.copytree(os.path.join(esky_root,"esky","tests","eskytester"),"eskytester")
      File "c:\depot\games\shared_tools\python\27\lib\shutil.py", line 168, in copytree
        names = os.listdir(src)
    WindowsError: [Error 3] The system cannot find the path specified: 'esky\\tests\\eskytester/*.*'

**Comment by timeyyy** [comment]
There is a small paragraph about testing in the contributing page of the wiki. Just install with pip
