### ISSUE TITLE
Patches fail to apply when new files are introduced into the appdata application folder

### ISSUE THREAD

**Issue by aodj** [cloudmatrix/esky#27]
If the build folder, under appdata, contains a new file, such as a log file or crash dump, any attempt to apply a patch will result in a full install download, which is considerably larger than the `bsdiff4` based patch.

The problem lies in the `calculate_digest` function which walks the entire directory of the application. If a file has been created in the build folder, or the user has created a file, such as a shortcut, it will be added to the calculated hash. Since the file doesn't exist at the time the patch is created, the calculated hash and read hash won't match and a `PatchError` exception is raised. This is silently caught by the update mechanism, and the full (new) build is downloaded.

**Comment by timeyyy** [comment]
What is actually the point of the verification step?
