### ISSUE TITLE
Stopping updater infinite loop

### ISSUE THREAD

**Issue by RuudBurger** [cloudmatrix/esky#29]
I've come acrosse issue #6 and found out I used an older version on my Windows setup. 

I somehow was building my app on Windows with 0.9.5 and found out to late. Now I assume users who are using the Couchpotato 2.0.1 ( which is build with 0.9.5 ) aren't able to upgrade automatically, but need to do it manually?

My updater points to http://couchpota.to/updates/ which then points to files on https://github.com/RuudBurger/CouchPotatoServer/downloads. As you can see, the window update is bugged, with a few hundred requests per second. Even if I remove the update from http://couchpota.to/updates/ the requests continue. Is the url cached somewhere, because every connected client should not be able to find the updates anymore..

Do you know a fix I can maybe implement on the server (returning 404 or whatever) that stop the updater.

**Comment by timeyyy** [comment]
Stale / related to issue 35
