### ISSUE TITLE
Bootstrapping with Recent PyPy

### ISSUE THREAD

**Issue by alexjc** [cloudmatrix/esky#31]
I've tried the procedures recommended here to build the bootstrap module with PyPy, but failed to get it working with the 1.8 and 1.9 versions.  I noticed the documentation says 1.5 and above, but that doesn't seem to be the case anymore.

Which is the last known version of PyPy to compile the bootstrap module successfully?  Would there be any down-sides to using an older PyPy or is it best to port the bootstrap code so it compiles with more recent versions of PyPy?

Thanks!

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
