### ISSUE TITLE
+x permissions lost when compiling zipfile on MacOS

### ISSUE THREAD

**Issue by aodj** [cloudmatrix/esky#34]
When using Python 2.7.2 and MacOS X  10.7 and creating my app, I appear to be losing the +x flag on the contents of the `<app>/Contents/MacOS/` folder. This contains `python` and my application bootstrapper.

Using the Python zipfile module to query their modes gives this:

```
>>> import zipfile
>>> zip = zipfile.ZipFile('dist/myapp-1.0.0.macosx-10_3-fat.zip', 'r')
>>> print oct(zip.getinfo('myapp.app/Contents/MacOS/python').external_attr >> 16L)
'0100644L'
```

This handy [stackoverflow question](http://stackoverflow.com/questions/279945/set-permissions-on-a-compressed-file-in-python) discusses the external_attr attribute on ZipInfo objects

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
