### ISSUE TITLE
Highest version is found but href isn't used on Windows

### ISSUE THREAD

**Issue by RuudBurger** [cloudmatrix/esky#35]
(Remember that this works for OSX so it isn't a link problem or anything.)

I have a problem with the updater where it finds the highest new version but does not add the href to `self._links`.
Using the `auto_update` with a callback. https://github.com/RuudBurger/CouchPotatoServer/blob/desktop/couchpotato/core/_base/updater/main.py#L404

When links are added via `VersionGraph.add_link`, it only adds an empty dict.

Example html with 1 version in the download_url:

```
CouchPotato-2.0.1.1.macosx-10_6-intel.zip
CouchPotato-2.0.1.1.win32.installer.exe
CouchPotato-2.0.1.1.win32.zip
```

self._links returns:

```
{
    '': {
        u '2.0.1.1': {}
    },
    u '2.0.1.1': {}
}
```

Example html with 2 versions in the download_url:

```
CouchPotato-2.0.2.macosx-10_6-intel.zip
CouchPotato-2.0.2.win32.installer.exe
CouchPotato-2.0.2.win32.zip
CouchPotato-2.0.1.1.macosx-10_6-intel.zip
CouchPotato-2.0.1.1.win32.installer.exe
CouchPotato-2.0.1.1.win32.zip
```

self._links returns:

```
{
    '': {
        u '2.0.1.1': {
            u 'https://github.com/downloads/RuudBurger/CouchPotatoServer/CouchPotato-2.0.1.1.win32.zip': 40
        },
        u '2.0.2': {}
    },
    u '2.0.1.1': {},
    u '2.0.2': {}
}
```

Example html with 3 versions in the download_url:

```
CouchPotato-2.0.3.macosx-10_6-intel.zip
CouchPotato-2.0.3.win32.installer.exe
CouchPotato-2.0.3.win32.zip
CouchPotato-2.0.2.macosx-10_6-intel.zip
CouchPotato-2.0.2.win32.installer.exe
CouchPotato-2.0.2.win32.zip
CouchPotato-2.0.1.1.macosx-10_6-intel.zip
CouchPotato-2.0.1.1.win32.installer.exe
CouchPotato-2.0.1.1.win32.zip
```

self._links returns:

```
{
    '': {
        u '2.0.1.1': {
            u 'https://github.com/downloads/RuudBurger/CouchPotatoServer/CouchPotato-2.0.1.1.win32.zip': 40
        },
        u '2.0.3': {},
        u '2.0.2': {
            u 'https://github.com/downloads/RuudBurger/CouchPotatoServer/CouchPotato-2.0.2.win32.zip': 40
        }
    },
    u '2.0.1.1': {},
    u '2.0.3': {},
    u '2.0.2': {}
}
```

Now as you can see, it keeps ignoring the highest version. Resulting in an always failing update.
It will thus always fire:

```
if path is None:
                raise EskyVersionError(version)
```

Seems like something is handled differently on Windows, as some test data (appending all the hrefs to a list): 

```
[u'https://github.com/downloads/RuudBurger/CouchPotatoServer/CouchPotato-2.0.3.win32.zip', u'https://github.com/downloads/RuudBurger/CouchPotatoServer/CouchPotato-2.0.2.win32.zip', u'https://github.com/downloads/RuudBurger/CouchPotatoServer/CouchPotato-2.0.1.1.win32.zip']
```

Could you please help me out with this, been trying to resolve this all day, but haven't found a solution..

**Comment by timeyyy** [comment]
@ruudburger did we see any further progress here?

**Comment by RuudBurger** [comment]
I moved the instal to a user directory. Not needing any admin rights for updates. Don't have the issue anymore as far as I can tell

**Comment by timeyyy** [comment]
The master branch of esky received a patch a while ago which adressed a similar issue, it might have fixed this one as well, would you be able to test if that is the case?

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
