### ISSUE TITLE
Support for Windows services

### ISSUE THREAD

**Issue by hexedpackets** [cloudmatrix/esky#39]
I've been unable to get a service build with esky working using cx_Freeze. I tried the normally recommended method of extending `win32serviceutil.ServiceFramework`, but the binary immediately fails with a timeout error. There is a also the `Win32Service` base built into cx_Freeze which has its own way of doing Windows services; however, I found a few problems with this.
1. There is no way to pass the base parameter to the esky Executable class. The only values it will ever set are `None` or `Win32GUI`.
2. I tried just passing base through instead of defaulting to None, but then ran into errors with  the startup hooks. The `cx_Freeze__init__` script ended up with an invalid sys module that surfaced by throwing an error about not having the attribute argv.

For the second problem, setting `dont_run_startup_hooks` to true seems to partially resolve the problem. I still couldn't run the base executable, but I was able to install and start the version-specific exe as a service.

I ended up working around this by splitting my code into two executables - the code that runs as a service is frozen directly by cx_Freeze and spawns a subprocess for the rest of the esky-frozen executable. Obviously this means that the service isn't automatically updated, though.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
