### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by voc2brain** [cloudmatrix/esky#57]
Hi guys, I get a error message on Windows and can't figure out how to solve this:
![screen shot 2014-01-25 at 21 51 36](https://f.cloud.github.com/assets/4704377/2003939/4c8ce630-8686-11e3-9d7e-8d70e451d05c.png)

I already tried to restart the computer but nothing changed. I also get the same error with cxfreeze ...

My setup.py code:
    example = Executable("gui_starter.py",
      gui_only=False,
       )

    setup(
      data_files=data_files,
      name = "Voc2brain",
      version = "4.4.%d" % subversion,
      scripts = [example],
      options = {"bdist_esky":{
                 #  forcibly include some other modules
                 "includes": ["sip", "lxml"],
                 #  forcibly exclude some other modules
                 "excludes": ["pydoc"],
                 #  force esky to freeze the app using py2exe
                 "freezer_module": "py2exe",
                 #  tweak the options used by py2exe
                 "freezer_options": {"bundle_files":3,"compressed":True},
              }}
    )

**Comment by kinnarr** [comment]
I had the same problem. While packing with py2exe directly I found some errors in my script. After fixing that, bdist_esky run without errors.

**Comment by timeyyy** [comment]
Errors not caused by esky
