### ISSUE TITLE
symlink breaks app

### ISSUE THREAD

**Issue by ksalman** [cloudmatrix/esky#62]
I am using an application that was packaged with esky. It works okay if I run from the directory or using a full path

```
root@unknown:~# /opt/salt/bin/salt-call state.sls packages.ntp
```

But it breaks if i symlink the executable to, for example, `/usr/bin`

```
root@unknown:~# ls -l /usr/bin/salt-call
lrwxrwxrwx 1 root root 23 Apr 10 09:03 /usr/bin/salt-call -> /opt/salt/bin/salt-call

root@unknown:~# /usr/bin/salt-call state.sls packages.ntp
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 685, in <module>
  File "__main__.py", line 331, in bootstrap
RuntimeError: no usable frozen versions were found
```

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
