### ISSUE TITLE
bdist_esky doesn't include all script files

### ISSUE THREAD

**Issue by Jnesselr** [cloudmatrix/esky#63]
The code is currently here: https://github.com/Hoektronics/bumblebee
The two different logs are here: https://drive.google.com/folderview?id=0B8yScqjnZ_daM3REazBNcHdFZVk&usp=sharing

I ran both python setup.py sdist and python setup.py bdist_esky

I can't figure out why it's not working. I'd like it to call bumblebee.py when it starts up because my __main__.py file doesn't currently work.

I'm new to the whole setup stuff, so can someone explain what the difference between sdist and bdist_esky are? I'm using bbfreeze on the raspberry pi if that helps.

The reason I filed a bug report is because I think that it's not reading the MANAFEST.in file.

**Comment by timeyyy** [comment]
@jnesselr did you sort this  out ? Have a read of the wiki there is a bit about working with data files, you need to allways run bdist_esky to make the script work with esky
