### ISSUE TITLE
Bootstrapped exe error: "ValueError: bad marshal data"

### ISSUE THREAD

**Issue by ghost** [cloudmatrix/esky#67]
I'm using:
Python 3.4.1
cx_Freeze 4.3.3
Esky 0.9.8
Windows 8

When I attempt to build the tutorial code that prints hello world, the cx_freeze example.exe works, but the esky bootstrapped example.exe gives the following error.
```
ValueError: bad marshal data (unknown type code)
Fatal Python error: unable to locate initialization module

Current thread 0x000024d0 (most recent call first):
```

The setup.py script is as follows:
```
import sys
from esky import bdist_esky
from distutils.core import setup

if sys.platform in ['win32', 'cygwin', 'win64']:
    setup(
        name = "example-app",
        version = "0.3",
        scripts = ["example.py"],
        options = {"bdist_esky": {
                  "freezer_module":"cxfreeze",
                }}
    )
```

**Comment by mvbentes** [comment]
Just to note thas as of 07/30/2015 the issue remais on the pypi version of esky, but it seems corrected on the master version.
Installing from the repo fixed it for me. Thank you all for the great work and valuable contributions!

**Comment by timeyyy** [comment]
Pypi has been updated
