### ISSUE TITLE
app.fetch_version() only works on newest version

### ISSUE THREAD

**Issue by UtahDave** [cloudmatrix/esky#69]
Running   esky 0.9.8 on Windows Server 2008 R2 Datacenter

If I run app.fetch_version('2014.99.0') where 2014.99.0 is the newest version of my software in the update_url it works fine.

If I run app.fetch_version('2014.80.0') then I get an error and it is unable to download the older version.

**Comment by timeyyy** [comment]
@UtahDave any more on this?
