### ISSUE TITLE
Tutorial on Mac OS X

### ISSUE THREAD

**Issue by atopuzov** [cloudmatrix/esky#7]
Hi,

Just wanted to pop a quick note on running the tutorial on Mac OS X (stage1 onwards).
There is a problem with running the apps as they are named "example-app" and you get in your **boot**.py:

```
__esky_name__ = 'example\-app'
```

It's because of the (in f_py2app.py): 

```
esky_name = re.escape(dist.distribution.get_name())
```

And it gets escaped as:

```
>>> import re
>>> re.escape("example-app")
'example\\-app'
```

I just changed the name form "example-app" to "exampleapp" and it works now.

Best regards
Aleksandar

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
