### ISSUE TITLE
Error packaging with py2app

### ISSUE THREAD

**Issue by jazzycamel** [cloudmatrix/esky#70]
When trying to build a simple test app (EskyExample) using Python3.3.3 and PyQt5 on OSX 10.9.3 (Mavericks) I get the following error when running "python3 setup.py bdist_esky":

<pre>
error: can't copy 'dist/EskyExample-0.0.1.macosx-10_6-intel/EskyExample-0.0.1.macosx-10_6-intel/EskyExample.app/Contents/Resources/lib/python3.3/config': doesn't exist or not a regular file
</pre>

When I look in the directory there is a sub-directory called "config3.3m" which I'm guessing is the required object but with a different name. 

Have I got something misconfigured somewhere or is this a bug when using Python3.3?

I'm using esky 0.9.8 and py2app 0.9, both installed via easy_install.

I would appreciate any help or advice you can give, thanks.

**Comment by JPFrancoia** [comment]
I do have the same issue, but with python 3.4 and esky 0.9.9. It seems that esky is not capable of identifying correctly the file (which is a directory actually) to copy. Has this issue been solved yet ?

**Comment by timeyyy** [comment]
unfortunately i don't have a mac, all i can is say is run the tests and go from there, ryan seems busy these days :( https://github.com/cloudmatrix/esky/wiki/Contributing

**Comment by timeyyy** [comment]
@JPFrancoia im sure you are capable enough ^^

**Comment by JPFrancoia** [comment]
Actually, esky with py2app will not work with python2 after this modification.
