### ISSUE TITLE
find_versions improvement request

### ISSUE THREAD

**Issue by stephanelsmith** [cloudmatrix/esky#75]
Url's are not required to have quotes, see:
https://developers.google.com/speed/pagespeed/module/filter-quote-remove

This breaks find_version regular expression which requires quote.
link_re = "href=['\"](?P<href>([^'\"]*/)?%s)['\"]" % (filename_re,)

recommended fix making quotes optional:

link_re = "href=['\"]?(?P<href>([^'\"]*/)?%s)['\"]?" % (filename_re,)

Commit coming....

**Comment by stephanelsmith** [comment]
An example, current expectation is file name is surrounded by ", eg.
<a href="xxxx-0.0.17.win32.zip">xxxx-0.0.17.win32.zip</a>

However, this is valid html syntax as well.
<a href=xxxx-0.0.17.win32.zip>xxxx-0.0.17.win32.zip</a>

Suggesting updating regex as mentioned above.

**Comment by rfk** [comment]
Fixed by #76
