### ISSUE TITLE
The boostrap.exe doesn't work when it is on the root folder (on Windows)

### ISSUE THREAD

**Issue by gschizas** [cloudmatrix/esky#79]
It seems that when the generated exe file is on the root folder (e.g. on a USB Flash Disk), esky doesn't detect the correct folder it's running in, and since it can't find it, it exists immediately with an exception

I have the following files on an USB flash disk:

      U:\
      ├  esky_test.exe
      ├  python34.dll
      └──appdata
         └──esky_test-0.1.win32
            ├  esky_test.exe
            ├  library.zip
            ├  msvcp100.dll
            ├  MSVCR100.dll
            ├  pyexpat.pyd
            ├  python34.dll
            ├  pywintypes34.dll
            ├  select.pyd
            ├  unicodedata.pyd
            ├  win32api.pyd
            ├  win32wnet.pyd
            ├  _bz2.pyd
            ├  _ctypes.pyd
            ├  _hashlib.pyd
            ├  _lzma.pyd
            ├  _multiprocessing.pyd
            ├  _socket.pyd
            ├  _ssl.pyd
            └──esky-files
               └  bootstrap-manifest.txt

When I run U:\esky_test.exe, I get the following error:

      Traceback (most recent call last):
        File "cx_Freeze__init__.py", line 747, in <module>
        File "cx_Freeze__init__.py", line 336, in bootstrap
        File "cx_Freeze__init__.py", line 363, in chainload
        File "cx_Freeze__init__.py", line 733, in _chainload
        File "«VirtualEnvRoot»\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
          exec(code, m.__dict__)
        File "«TempFolder»\scripts\esky_test.py", line 2, in <module>
        File "«VirtualEnvRoot»\lib\site-packages\esky\__init__.py", line 1092, in run_startup_hooks
          lock_version_dir(vdir)
        File "«VirtualEnvRoot»\lib\site-packages\esky\bootstrap.py", line 649, in lock_version_dir
          _locked_version_dirs.setdefault(vdir,[]).append(os_open(lockfile,0,0))
      FileNotFoundError: [Errno 2] No such file or directory: 'U:\\esky_test-0.1.win32\\esky-files\\bootstrap-manifest.txt'

If I take all the files on `U:\` and move them to any folder (within U:\), it works without any other problem.

The setup.py is simply this:

    #!/usr/bin/env python3.4-32
    # -*- coding: utf-8 -*-
    
    from esky import bdist_esky
    from distutils.core import setup
    
    
    setup(
        name="esky_test",
        version="0.1",
        scripts=['esky_test.py'],
        options={'bdist_esky': dict(
            freezer_module='cx_Freeze',
            freezer_options=dict(includeMSVCR=True),
            enable_appdata_dir=True,
            bundle_msvcrt=True
        )}
    )

and the actual `esky_test.py` is simply this:

    print("hi!")

**Comment by gschizas** [comment]
Note: For testing, you can use Windows' SUBST.EXE to simulate a flash drive:

    @echo off
    SUBST U: «project folder»\dist
    U:
    esky_test.exe
    REM this fails
    C:

**Comment by gschizas** [comment]
I have made the fix, at https://github.com/gschizas/esky/commit/1a20ca9cfbeee0c68fdfd9bf222a4ed12e1f3b55, but since the master branch is a fair bit behind, I'm not making a pull request yet.

The problem is that the dirname of a file that is on the root folder is `U:\` (with a final backslash), but if it isn't on the root, it's `U:\dirname` (without a final backslash). This messes up the appdir discovery, and it ends up believing that appdir is at the root.

**Comment by rfk** [comment]
Thanks for digging into this!  I won't have time to look at it in any detail until after PyCon but I'll try to get on top of it soon after.  Don't hesitate to bump this if it looks like I've forgotten.

**Comment by gschizas** [comment]
Bumping this, since PyCon must be over by now :)

**Comment by rfk** [comment]
Right you are, thanks for the bump, I'll keep this in my inbox until I've given it a proper look.

**Comment by rfk** [comment]
@gschizas your fix looks good to me; what do you need before you can spin it into a PR?  (I won't be surprised that something's out of date on this project, but I'm not sure exactly what bit you're referring to above)

**Comment by gschizas** [comment]
As you can see on the [comparison page](https://github.com/cloudmatrix/esky/compare/master...gschizas:master), I have incorporated all of @Darkman802's changes - otherwise it doesn't work with Python 3.3.

My git-fu isn't very strong, so I'm not sure how I could do a pull request for the three commits that fix the problem:

https://github.com/cloudmatrix/esky/commit/d06bde62c94563cd8abceae7055df8edfd4d2349
https://github.com/cloudmatrix/esky/commit/596a9014f804a6b9bed1072a7ef73acbdf880264
https://github.com/cloudmatrix/esky/commit/1a20ca9cfbeee0c68fdfd9bf222a4ed12e1f3b55

**Comment by rfk** [comment]
I incorporated your fix in 74be2fd98dd9ca2c16c5aa8eee75caf309552445, thanks very much!
