### ISSUE TITLE
Code signing bootstrap exe

### ISSUE THREAD

**Issue by bgr** [cloudmatrix/esky#84]
Hello,
I'm getting an error `cx_Freeze Fatal Error - cannot get zipimporter instance` after code-signing the bootstrap exe. Is there a combination of options that'll allow esky's bootstrap exe to be signed successfuly?

Note that the exe in appdata/appname-xxx/ works correctly after signing - at first I was getting the same error but I've managed to get rid of it by using the combination of cx_freeze's options (`'createLibraryZip': True, 'appendScriptToExe': False`). Are there similar options for esky itself?

**Comment by rfk** [comment]
Unfortunately `appendScriptToExe: false` doesn't work for the bootstrap exe, because it depends on having the code bundled in an appended zipfile.  This makes the bootstrap exe a single atomic unit, but it interacts badly with codesigning.

**Comment by bgr** [comment]
Is code signing support something to be expected (preferably in the near future)?

**Comment by rfk** [comment]
No, sorry - unfortunately I don't have much time to work on the project these days :-(

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
