### ISSUE TITLE
update faq

### ISSUE THREAD

**Issue by timeyyy** [cloudmatrix/esky#85]
New additions to the faq, as far as i know wikis cannot be pulled so im just pasting the additions here

## How do i include data files in Esky?
    setup(name="MyApp",
        data_files=[('', ['MyApp.xib']),
                    ('files', ['file1', 'file2']),
                    ('img', glob(r'.\img\*.*'))
                   ]
        ...

## Why is Esky not finding frozen versions on my server?
Check firewall/antivirus are not blocking the port/program.

## Why does esky create 2 executables?
Esky uses a bootstrapping mechanism that keeps the app safe in the face of failed or partial updates.

The top level executable is the one you should be running, it does all the business of managing what version to run. Once it has decided what to run it will run the correct version.

## How do i hide the console window?
    from esky.bdist_esky import Executable  
    executables = [Executable('ham.py', icon='spam.ico', gui_only=True)]
    setup(name="hellow world",
        version = '0.1',
        scripts = executables)

**Comment by rfk** [comment]
:+1: 

Do you have access to make these edits directly in the wiki?  If not, I'll happily figure out how to grant it.

**Comment by timeyyy** [comment]
oh, i wasn't aware that i had write access to the wiki.
