### ISSUE TITLE
Python3.5 compatibility

### ISSUE THREAD

**Issue by alvaromlg** [cloudmatrix/esky#95]
Looks like this code https://github.com/cloudmatrix/esky/blob/master/esky/util.py#L578 wont work in python3.5 since _bootstrap hasnt those method/classes.

It looks like its working replacing _bootstrap with _bootstrap_external:

        loader = importlib._bootstrap_external.SourceLoader()    
        code = loader.source_to_code(source_code, '<string>')
        bytecode = importlib._bootstrap._external_code_to_bytecode(code, mtime=0, source_size=0)

Is it python3.5 compatible? or just until python3.4

**Comment by timeyyy** [comment]
esky development has slowed, the plan is to make esky compatabile with python3 without needing to run 2to3 converter, this will make debugging and programming for python3 much easier. You can read up on the latest issues here https://github.com/cloudmatrix/esky/issues/90.

Status of 3.5 is unknown

**Comment by timeyyy** [comment]
@alvaromlg did the latest patch fix the issue?

**Comment by alvaromlg** [comment]
Yes, looks like it's working for me

2015-11-03 22:15 GMT+01:00 tim <notifications@github.com>:

> @alvaromlg <https://github.com/alvaromlg> did the latest patch fix the
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudmatrix/esky/issues/95#issuecomment-153491274>.
>



-- 

*Álvaro Pelegrina Fernández*
Python / Angular JS Developer

Flumotion Services S.A.
World Trade Center - Ed. Norte - planta 7
Moll de Barcelona - 08039 - Barcelona - Spain
*www.flumotion.com <http://www.flumotion.com/>*
