### ISSUE TITLE
Is an .app file created on Mac OS ?

### ISSUE THREAD

**Issue by JPFrancoia** [cloudmatrix/esky#98]
Hi,

I'm normally not a mac user (I'm a linux one), but I would like to provide a mac version of the program I developed. However, I encounter some problems.

I use cx_freeze as a freezer, because it works both for linux and windows. ```python3 setup.py bdist_esky``` works perfectly, and a zip of my program is created in the dist folder. Unzipping it and running it also works.

But now, I would like to create an installer for my program (like one you could create with Inno setup). All the tutorials I found online use a .app file to create their installer package.

Am I supposed to get a .app file when I compile my program with Esky ?

**Comment by timeyyy** [comment]
@JPFrancoia did u sort this out?

**Comment by JPFrancoia** [comment]
Not really, I finally decided to use py2app (which gave me more issues...). It does create a .app. I think we can close it.
