### ISSUE TITLE
Hard coded Python 3-style exec(....) statement in f_py2exe.py

### ISSUE THREAD

**Issue by david-hughes** [cloudmatrix/esky#99]
In github, esky/bdist_esky/f_py2exe.py line 379-380 says

      for code in codelist:
          exec(code, d_globals, d_locals)

but Python 2.x requires the syntax

      for code in codelist:
          exec code in d_globals, d_locals

I guess this requires conditional coding depending on the version of Python being used, as is done in f_cxfreeze.py

David Hughes
Forestfield Software

**Comment by timeyyy** [comment]
Thanks for the feedback david

**Comment by david-hughes** [comment]
Re #99 I think the conditional test needs to be against *sys.version_info[0]* not sys.version[0] but even with that it still isn't working (I thought it was originally). The block of 'code' containing this change is actually a long text string that gets loaded into "something" and gets executed. So I think the version2/version3 test needs to be outside this block - like it is in f_cxfreeze.py. I will have another look at it tomorrow.

**Comment by david-hughes** [comment]
The following change shamelessly borrowed from f_cxfreeze seems to be working OK

![f_py2exe-diff](https://cloud.githubusercontent.com/assets/2462978/11400181/b77d4c08-9383-11e5-9666-d38d7144d0c1.png)
